# Generated by Django 5.2.9 on 2025-12-18 13:51

import cloudinary.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'Lost Dog'), ('found', 'Found Dog')], help_text='Whether this is a lost or found dog listing', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('found', 'Found'), ('returned', 'Returned to Owner')], default='active', help_text='Current status of the listing', max_length=20)),
                ('title', models.CharField(help_text='Brief title for the listing', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the dog and circumstances')),
                ('breed', models.CharField(blank=True, help_text='Dog breed (if known)', max_length=100, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small (up to 10kg)'), ('medium', 'Medium (10-25kg)'), ('large', 'Large (25kg+)')], help_text='Approximate size of the dog', max_length=10, null=True)),
                ('color', models.CharField(blank=True, help_text='Primary color of the dog', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text="Dog's gender (if known)", max_length=10)),
                ('has_collar', models.BooleanField(default=False, help_text='Whether the dog has a collar')),
                ('collar_color', models.CharField(blank=True, help_text='Color of the collar (if present)', max_length=50, null=True)),
                ('dog_name', models.CharField(blank=True, help_text="Dog's name (if known)", max_length=100, null=True)),
                ('age_estimate', models.CharField(blank=True, help_text="Estimated age (e.g., 'puppy', '2 years', 'senior')", max_length=20, null=True)),
                ('microchip_number', models.CharField(blank=True, help_text='Microchip number (if known)', max_length=50, null=True)),
                ('special_marks', models.TextField(blank=True, help_text='Any distinctive marks, scars, or features', null=True)),
                ('reward_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount (if any)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fostering_address', models.CharField(blank=True, help_text='Address where dog is being fostered (if applicable)', max_length=255, null=True)),
                ('search_radius_km', models.IntegerField(default=5, help_text='Search radius in kilometers (1-50km)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this listing expires', null=True)),
                ('user', models.ForeignKey(help_text='User who created this listing', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic coordinates (longitude, latitude)', srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True)),
                ('area_radius_meters', models.IntegerField(default=0, help_text='Radius for approximate locations (meters)')),
                ('address', models.CharField(blank=True, help_text='Human-readable address', max_length=500, null=True)),
                ('location_type', models.CharField(choices=[('exact', 'Exact Location'), ('approximate', 'Approximate Area')], default='exact', help_text='Exact or approximate location', max_length=15)),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary/most recent location')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this location', null=True)),
                ('accuracy_meters', models.IntegerField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_user', models.ForeignKey(help_text='User who added this location update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_locations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Listing this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', cloudinary.models.CloudinaryField(help_text='Photo stored in Cloudinary', max_length=255, verbose_name='photo')),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID', max_length=255)),
                ('thumbnail_url', models.CharField(blank=True, help_text='Thumbnail URL', max_length=500)),
                ('order_index', models.IntegerField(default=0, help_text='Order of photo display (0 = primary)')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='Listing this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order_index', 'uploaded_at'],
            },
        ),
    ]
