# Generated by Django 5.2.9 on 2025-12-19 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='search_radius_km',
            field=models.IntegerField(default=5, help_text='Search radius in kilometers (1-10km)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
